services:
  ahack-web:
    build: .
    command: ahack run-server
    ports:
      - "80:8888"
    env_file:
      - 'pg_config.env'
    depends_on:
      - postgres

  ahack-llm:
    build: .
    command: ahack llm-pipeline
    env_file:
      - 'pg_config.env'
      - 'llm_credentials.env'
    depends_on:
      - postgres
    volumes:
      - './models:/models'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ahack-experiments:
    build: .
    command: ahack do
    env_file:
      - 'pg_config.env'
      - 'llm_credentials.env'
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: pgvector.dockerfile
    ports:
      - "5432:5432"
    env_file:
      - 'pg_config.env'
    volumes:
      - "./src/atomic_hack/database/postgres:/docker-entrypoint-initdb.d"
      - "postgres-data:/var/lib/postgresql/data"
    logging:
      driver: none

volumes:
  postgres-data:
    driver: local
