services:
  ahack-web:
    build: .
    command: ahack run-server
    ports:
      - "8888:8888"
    env_file:
      - 'pg_config.env'
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: pgvector.dockerfile
    ports:
      - "5432:5432"
    env_file:
      - 'pg_config.env'
    volumes:
      - "./src/atomic_hack/database/postgres:/docker-entrypoint-initdb.d"
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
    driver: local
